The Process of chossing the optimal parameter for a given model or different models which produces the best result is Hyperparameter

In [3]:
from sklearn import svm, datasets
iris = datasets.load_iris()

In [12]:
import pandas as pd
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["flower"] = iris.target
df["flower"] = df["flower"].apply(lambda x: iris.target_names[x])
df[47:52]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   

        flower  
47      setosa  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)



In [24]:
model = svm.SVC(kernel="rbf", C=30, gamma="auto")
model.fit(X_train, y_train)
model.score(X_test, y_test)
#As we see the score changes as we run the train_test_split and the model so we use cross validation to fix this issue

0.9777777777777777

In [25]:
from sklearn.model_selection import cross_val_score

In [26]:
cross_val_score( svm.SVC(kernel="linear", C=10, gamma="auto"), iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [27]:
cross_val_score( svm.SVC(kernel="rbf", C=10, gamma="auto"), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [28]:
cross_val_score( svm.SVC(kernel="rbf", C=20, gamma="auto"), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [34]:
import numpy as np
import pandas as pd

In [37]:
#Using a for loop for the code above
kernels = ["rbf", "linear"]
c = [1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in c:
        cv_scores = cross_val_score(svm.SVC(kernel=kval, C=cval, gamma="auto"), iris.data, iris.target, cv=5)
        avg_scores[kval + "_" + str(cval)] = np.average(cv_scores)
        
avg_scores        
#But this method is not also convinent as if we have for like 5 kernels we will have like 5 loops whic becomes much more complicated, But sklearn provides a function
#Called GRIDSearchCV

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

In [38]:
from sklearn.model_selection import GridSearchCV

In [40]:
clf = GridSearchCV(svm.SVC(gamma="auto"), {

clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00180645, 0.00127039, 0.00167809, 0.00120983, 0.0009006 ,
        0.00019898]),
 'std_fit_time': array([0.00040694, 0.00038584, 0.00055469, 0.00042005, 0.00019794,
        0.00039797]),
 'mean_score_time': array([0.00133677, 0.00204644, 0.00050564, 0.00080004, 0.0008049 ,
        0.00101562]),
 'std_score_time': array([2.60166365e-04, 5.99063193e-04, 4.37083578e-04, 4.00018706e-04,
        4.02540410e-04, 2.37661112e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20

In [41]:
#Cv Results are not easy to view , but sklern provides a way it can be dowloaded to a dataframe

In [46]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001806      0.000407         0.001337        0.000260       1   
1       0.001270      0.000386         0.002046        0.000599       1   
2       0.001678      0.000555         0.000506        0.000437      10   
3       0.001210      0.000420         0.000800        0.000400      10   
4       0.000901      0.000198         0.000805        0.000403      20   
5       0.000199      0.000398         0.001016        0.000024      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [47]:
df[["param_C", "param_kernel", "mean_test_score"]] #As we see with gridsearchcv it is more convinient even with more parameter as 
#GridSearchCv does the permutation and combinations of all of them.

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [49]:
dir(clf) #Checking what other parameters can be used on the clf object

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs

In [50]:
clf.best_score_

0.9800000000000001

In [51]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [52]:
#A disadvantage of GridSearchCv is the computation cost as it computes the combination and permutation of all values with a very hight computation cost 
#Therefore sklearn came up with RandomizedSearchCV which trys random computation of the parameter values



In [55]:
from sklearn.model_selection import RandomizedSearchCV

In [58]:
rs = RandomizedSearchCV(svm.SVC(gamma="auto"),{
    "C":[1, 10, 20],
    "kernel":["rbf","linear"]
}, cv=5, return_train_score=False,n_iter=2)
rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[["param_C", "param_kernel", "mean_test_score"]]

param_C param_kernel  mean_test_score
0      10       linear         0.973333
1       1       linear         0.980000

## Choosing model for a given problem

In [60]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression


In [62]:
model_params = {
    "svm":{
        "model": svm.SVC(gamma="auto"),
        "params": {
            "C": [1,10,20],
            "kernel": ["rbf", "linear"]
        }
    },
    "random_forest":{
        "model": RandomForestClassifier(),
        "params": {
            "n_estimators": [ 1, 5, 10]
        }
    },
    "logistic_regression":{
        "model": LogisticRegression(solver="liblinear", multi_class="auto"),
        "params": {
            "C": [1, 4, 10]
        }
    }
}

In [74]:
scores = []
for model_name, mp in model_params.items():
    clf = GridSearchCV(mp["model"], mp["params"], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        "model": model_name,
        "best_score":clf.best_score_,
        "best_params":clf.best_params_
    })

In [75]:
df = pd.DataFrame(scores, columns=["model", "best_score", "best_params"])

In [76]:
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.966667       {'n_estimators': 10}
2  logistic_regression    0.966667                   {'C': 4}

In [77]:
#As we can see svm performs better than the two other models which makes it the best out of all

## Thanks